- hosts: all
  tasks:
    - name: Create User Operator
      user:
        name: operator
        comment: JayDee
        shell: /bin/bash
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present        
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
    - name: Add sudoers users to wheel group
      user:
        name: operator
        groups: wheel
        append: yes
    - name: Set authorized key defining key options
      authorized_key:
        user: operator
        state: present
        key: "{{ lookup('file', '/home/devops/.ssh/id_ed25519.pub') }}"

#add wheel or sudoer group
#add the created goup 
#add sudoer to wheel group
#add ssh keys
#ansible tips and tricks os dependent tasks: task separation via variables